/**
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.6.2
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WoleetApi) {
      root.WoleetApi = {};
    }
    root.WoleetApi.Identity = factory(root.WoleetApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Identity model module.
   * @module model/Identity
   * @version 1.6.2
   */

  /**
   * Constructs a new <code>Identity</code>.
   * Signee&#39;s identity provided as a set of X.500 attributes (see https://www.ietf.org/rfc/rfc4519.txt).
   * @alias module:model/Identity
   * @class
   * @param commonName {String} commonName (CN) (2.5.4.3)
   */
  var exports = function(commonName) {
    var _this = this;

    _this['commonName'] = commonName;
  };

  /**
   * Constructs a <code>Identity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Identity} obj Optional instance to populate.
   * @return {module:model/Identity} The populated <code>Identity</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('commonName')) {
        obj['commonName'] = ApiClient.convertToType(data['commonName'], 'String');
      }
      if (data.hasOwnProperty('organization')) {
        obj['organization'] = ApiClient.convertToType(data['organization'], 'String');
      }
      if (data.hasOwnProperty('organizationalUnit')) {
        obj['organizationalUnit'] = ApiClient.convertToType(data['organizationalUnit'], 'String');
      }
      if (data.hasOwnProperty('locality')) {
        obj['locality'] = ApiClient.convertToType(data['locality'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
    }
    return obj;
  }

  /**
   * commonName (CN) (2.5.4.3)
   * @member {String} commonName
   */
  exports.prototype['commonName'] = undefined;
  /**
   * organizationName (O) (2.5.4.10)
   * @member {String} organization
   */
  exports.prototype['organization'] = undefined;
  /**
   * organizationalUnitName (OU) (2.5.4.11)
   * @member {String} organizationalUnit
   */
  exports.prototype['organizationalUnit'] = undefined;
  /**
   * localityName (L) (2.5.4.7)
   * @member {String} locality
   */
  exports.prototype['locality'] = undefined;
  /**
   * countryName (C) (2.5.4.6)
   * @member {String} country
   */
  exports.prototype['country'] = undefined;



  return exports;
}));


