/**
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReceiptTargetProofNode from './ReceiptTargetProofNode';

/**
 * The ReceiptTarget model module.
 * @module model/ReceiptTarget
 * @version 1.6.2
 */
class ReceiptTarget {
    /**
     * Constructs a new <code>ReceiptTarget</code>.
     * Chainpoint 1.x only
     * @alias module:model/ReceiptTarget
     */
    constructor() { 
        
        ReceiptTarget.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReceiptTarget</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReceiptTarget} obj Optional instance to populate.
     * @return {module:model/ReceiptTarget} The populated <code>ReceiptTarget</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReceiptTarget();

            if (data.hasOwnProperty('target_hash')) {
                obj['target_hash'] = ApiClient.convertToType(data['target_hash'], 'String');
            }
            if (data.hasOwnProperty('target_proof')) {
                obj['target_proof'] = ApiClient.convertToType(data['target_proof'], [ReceiptTargetProofNode]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} target_hash
 */
ReceiptTarget.prototype['target_hash'] = undefined;

/**
 * @member {Array.<module:model/ReceiptTargetProofNode>} target_proof
 */
ReceiptTarget.prototype['target_proof'] = undefined;






export default ReceiptTarget;

