/**
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReceiptTargetProofNode model module.
 * @module model/ReceiptTargetProofNode
 * @version 1.6.2
 */
class ReceiptTargetProofNode {
    /**
     * Constructs a new <code>ReceiptTargetProofNode</code>.
     * Chainpoint 1.x only
     * @alias module:model/ReceiptTargetProofNode
     */
    constructor() { 
        
        ReceiptTargetProofNode.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReceiptTargetProofNode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReceiptTargetProofNode} obj Optional instance to populate.
     * @return {module:model/ReceiptTargetProofNode} The populated <code>ReceiptTargetProofNode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReceiptTargetProofNode();

            if (data.hasOwnProperty('left')) {
                obj['left'] = ApiClient.convertToType(data['left'], 'String');
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = ApiClient.convertToType(data['parent'], 'String');
            }
            if (data.hasOwnProperty('right')) {
                obj['right'] = ApiClient.convertToType(data['right'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} left
 */
ReceiptTargetProofNode.prototype['left'] = undefined;

/**
 * @member {String} parent
 */
ReceiptTargetProofNode.prototype['parent'] = undefined;

/**
 * @member {String} right
 */
ReceiptTargetProofNode.prototype['right'] = undefined;






export default ReceiptTargetProofNode;

