/**
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReceiptHeader model module.
 * @module model/ReceiptHeader
 * @version 1.6.2
 */
class ReceiptHeader {
    /**
     * Constructs a new <code>ReceiptHeader</code>.
     * Chainpoint 1.x only
     * @alias module:model/ReceiptHeader
     */
    constructor() { 
        
        ReceiptHeader.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReceiptHeader</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReceiptHeader} obj Optional instance to populate.
     * @return {module:model/ReceiptHeader} The populated <code>ReceiptHeader</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReceiptHeader();

            if (data.hasOwnProperty('chainpoint_version')) {
                obj['chainpoint_version'] = ApiClient.convertToType(data['chainpoint_version'], 'String');
            }
            if (data.hasOwnProperty('hash_type')) {
                obj['hash_type'] = ApiClient.convertToType(data['hash_type'], 'String');
            }
            if (data.hasOwnProperty('merkle_root')) {
                obj['merkle_root'] = ApiClient.convertToType(data['merkle_root'], 'String');
            }
            if (data.hasOwnProperty('tx_id')) {
                obj['tx_id'] = ApiClient.convertToType(data['tx_id'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} chainpoint_version
 * @default '1.0'
 */
ReceiptHeader.prototype['chainpoint_version'] = '1.0';

/**
 * @member {String} hash_type
 * @default 'SHA-256'
 */
ReceiptHeader.prototype['hash_type'] = 'SHA-256';

/**
 * @member {String} merkle_root
 */
ReceiptHeader.prototype['merkle_root'] = undefined;

/**
 * @member {String} tx_id
 */
ReceiptHeader.prototype['tx_id'] = undefined;

/**
 * @member {Number} timestamp
 */
ReceiptHeader.prototype['timestamp'] = undefined;






export default ReceiptHeader;

