/**
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.6.0
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WoleetApi) {
      root.WoleetApi = {};
    }
    root.WoleetApi.SignatureRequestSign = factory(root.WoleetApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The SignatureRequestSign model module.
   * @module model/SignatureRequestSign
   * @version 1.6.0
   */

  /**
   * Constructs a new <code>SignatureRequestSign</code>.
   * @alias module:model/SignatureRequestSign
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>SignatureRequestSign</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SignatureRequestSign} obj Optional instance to populate.
   * @return {module:model/SignatureRequestSign} The populated <code>SignatureRequestSign</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('signature')) {
        obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
      }
      if (data.hasOwnProperty('pubKey')) {
        obj['pubKey'] = ApiClient.convertToType(data['pubKey'], 'String');
      }
      if (data.hasOwnProperty('signeeId')) {
        obj['signeeId'] = ApiClient.convertToType(data['signeeId'], 'String');
      }
      if (data.hasOwnProperty('otp')) {
        obj['otp'] = ApiClient.convertToType(data['otp'], 'String');
      }
      if (data.hasOwnProperty('identityURL')) {
        obj['identityURL'] = ApiClient.convertToType(data['identityURL'], 'String');
      }
    }
    return obj;
  }

  /**
   * Signature of the `hashToSign` property of the signature request using the public key stored in the `pubKey` property. 
   * @member {String} signature
   */
  exports.prototype['signature'] = undefined;
  /**
   * Public key of the signee. 
   * @member {String} pubKey
   */
  exports.prototype['pubKey'] = undefined;
  /**
   * Secret identifier of the signee (only required if `email` was set for this signee). 
   * @member {String} signeeId
   */
  exports.prototype['signeeId'] = undefined;
  /**
   * One Time Password of the signee (only required if `requiresOTP` was set to `true` for thìs signee). 
   * @member {String} otp
   */
  exports.prototype['otp'] = undefined;
  /**
   * Web hook to use to verify the signee's identity. 
   * @member {String} identityURL
   */
  exports.prototype['identityURL'] = undefined;



  return exports;
}));


