/**
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * The version of the OpenAPI document: 1.13.0
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Tokens model module.
 * @module model/Tokens
 * @version 1.13.0
 */
class Tokens {
    /**
     * Constructs a new <code>Tokens</code>.
     * @alias module:model/Tokens
     * @param tokens {Array.<String>} Array of tokens.
     */
    constructor(tokens) { 
        
        Tokens.initialize(this, tokens);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tokens) { 
        obj['tokens'] = tokens;
    }

    /**
     * Constructs a <code>Tokens</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tokens} obj Optional instance to populate.
     * @return {module:model/Tokens} The populated <code>Tokens</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tokens();

            if (data.hasOwnProperty('tokens')) {
                obj['tokens'] = ApiClient.convertToType(data['tokens'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Array of tokens.
 * @member {Array.<String>} tokens
 */
Tokens.prototype['tokens'] = undefined;






export default Tokens;

