/**
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * The version of the OpenAPI document: 1.10.0
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import X500Name from './X500Name';

/**
 * The X509SubjectIssuer model module.
 * @module model/X509SubjectIssuer
 * @version 1.10.0
 */
class X509SubjectIssuer {
    /**
     * Constructs a new <code>X509SubjectIssuer</code>.
     * @alias module:model/X509SubjectIssuer
     */
    constructor() { 
        
        X509SubjectIssuer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>X509SubjectIssuer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/X509SubjectIssuer} obj Optional instance to populate.
     * @return {module:model/X509SubjectIssuer} The populated <code>X509SubjectIssuer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new X509SubjectIssuer();

            if (data.hasOwnProperty('subject')) {
                obj['subject'] = X500Name.constructFromObject(data['subject']);
            }
            if (data.hasOwnProperty('issuer')) {
                obj['issuer'] = X500Name.constructFromObject(data['issuer']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/X500Name} subject
 */
X509SubjectIssuer.prototype['subject'] = undefined;

/**
 * @member {module:model/X500Name} issuer
 */
X509SubjectIssuer.prototype['issuer'] = undefined;






export default X509SubjectIssuer;

