/**
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SignatureRequest from '../model/SignatureRequest';
import SignatureRequestSign from '../model/SignatureRequestSign';
import SignatureRequestSignResult from '../model/SignatureRequestSignResult';
import SignatureRequests from '../model/SignatureRequests';

/**
* SignatureRequest service.
* @module api/SignatureRequestApi
* @version 1.6.2
*/
export default class SignatureRequestApi {

    /**
    * Constructs a new SignatureRequestApi. 
    * @alias module:api/SignatureRequestApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createSignatureRequest operation.
     * @callback module:api/SignatureRequestApi~createSignatureRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SignatureRequest} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new signature request.
     * Use this operation to create a new signature request.<br> The properties `id`, `created` and `lastModified` are read-only and so must not be provided: they are managed by the platform and added to the returned request.<br> Only the properties `name` and `hashToSign` are required: the `hashToSign` property must be the SHA256 hash of the data to sign. This allows not to leak the original data and to keep the actual signed data small (signing the digest is equivalent to signing the original data).<br> Be sure to have enough signature and anchoring credits on your account to fulfill the signature request (each registered signature will cost you 1 signature and 1 anchoring credit).<br> 
     * @param {module:model/SignatureRequest} signatureRequest SignatureRequest object to create.
     * @param {module:api/SignatureRequestApi~createSignatureRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SignatureRequest}
     */
    createSignatureRequest(signatureRequest, callback) {
      let postBody = signatureRequest;
      // verify the required parameter 'signatureRequest' is set
      if (signatureRequest === undefined || signatureRequest === null) {
        throw new Error("Missing the required parameter 'signatureRequest' when calling createSignatureRequest");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth', 'JWTAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SignatureRequest;
      return this.apiClient.callApi(
        '/signatureRequest', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteSignatureRequest operation.
     * @callback module:api/SignatureRequestApi~deleteSignatureRequestCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a signature request.
     * Use this operation to delete a signature request.<br> 
     * @param {String} requestId Identifier of the signature request to delete.
     * @param {module:api/SignatureRequestApi~deleteSignatureRequestCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteSignatureRequest(requestId, callback) {
      let postBody = null;
      // verify the required parameter 'requestId' is set
      if (requestId === undefined || requestId === null) {
        throw new Error("Missing the required parameter 'requestId' when calling deleteSignatureRequest");
      }

      let pathParams = {
        'requestId': requestId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth', 'JWTAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/signatureRequest/{requestId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSignatureRequest operation.
     * @callback module:api/SignatureRequestApi~getSignatureRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SignatureRequest} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a signature request by its identifier.
     * Use this operation to retrieve a signature request by its identifier.<br> When accessed with no authentication, only public attributes of the signature request are returned. 
     * @param {String} requestId Identifier of the signature request to retrieve.
     * @param {Object} opts Optional parameters
     * @param {String} opts.signeeId Secret identifier of the signee wanting to retrieve the signature request.<br> If set, information related to this signee is returned in `authorizedSignees[0]`.<br> **This secret identifier is generated by the platform and only included in the email sent to the signee, allowing the platform to authenticate the signee.** 
     * @param {module:api/SignatureRequestApi~getSignatureRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SignatureRequest}
     */
    getSignatureRequest(requestId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'requestId' is set
      if (requestId === undefined || requestId === null) {
        throw new Error("Missing the required parameter 'requestId' when calling getSignatureRequest");
      }

      let pathParams = {
        'requestId': requestId
      };
      let queryParams = {
        'signeeId': opts['signeeId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth', 'JWTAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SignatureRequest;
      return this.apiClient.callApi(
        '/signatureRequest/{requestId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchSignatureRequests operation.
     * @callback module:api/SignatureRequestApi~searchSignatureRequestsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SignatureRequests} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search for signature requests.
     * Use this operation to retrieve all signature requests having a given `name` and/or `hashToSign` property.<br> Only requests belonging to the authenticated user are returned.<br> Paging and sorting is supported. 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page Index of the page to retrieve (from 0). (default to 0)
     * @param {Number} opts.size Number of anchors per page. (default to 20)
     * @param {module:model/String} opts.direction Sorting direction: ASC for ascending DESC for descending.  (default to 'ASC')
     * @param {module:model/String} opts.sort Sorting property: possible values are limited to `id`, `created` and `hashToSign`.  (default to 'created')
     * @param {String} opts.name `name` to search for: all signature requests whose `name` property contains this sub-string are returned.<br> **WARNING: Searching by name can timeout on a large signature request set.** 
     * @param {String} opts.hashToSign `hashToSign` to search for: all signature requests whose `hashToSign` property is equal are returned. 
     * @param {module:api/SignatureRequestApi~searchSignatureRequestsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SignatureRequests}
     */
    searchSignatureRequests(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'direction': opts['direction'],
        'sort': opts['sort'],
        'name': opts['name'],
        'hashToSign': opts['hashToSign']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth', 'JWTAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SignatureRequests;
      return this.apiClient.callApi(
        '/signatureRequests', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the sendSignatureRequestOTP operation.
     * @callback module:api/SignatureRequestApi~sendSignatureRequestOTPCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Generate and send an OTP to a signee of a signature request.
     * Use this operation to generate and send a new OTP (One Time Password) by SMS to a signee of a signature request.<br> This OTP can be used to sign during a maximum period of 10 mn. 
     * @param {String} requestId Identifier of the signature request.
     * @param {String} signeeId Secret identifier of the signee wanting to retrieve his OTP.<br> **This secret identifier is generated by the platform and only included in the email sent to the signee, allowing the platform to authenticate the signee.** 
     * @param {module:api/SignatureRequestApi~sendSignatureRequestOTPCallback} callback The callback function, accepting three arguments: error, data, response
     */
    sendSignatureRequestOTP(requestId, signeeId, callback) {
      let postBody = null;
      // verify the required parameter 'requestId' is set
      if (requestId === undefined || requestId === null) {
        throw new Error("Missing the required parameter 'requestId' when calling sendSignatureRequestOTP");
      }
      // verify the required parameter 'signeeId' is set
      if (signeeId === undefined || signeeId === null) {
        throw new Error("Missing the required parameter 'signeeId' when calling sendSignatureRequestOTP");
      }

      let pathParams = {
        'requestId': requestId,
        'signeeId': signeeId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth', 'JWTAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/signatureRequest/{requestId}/otp/{signeeId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the signSignatureRequest operation.
     * @callback module:api/SignatureRequestApi~signSignatureRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SignatureRequestSignResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Sign a signature request.
     * Use this operation to register a signature in a signature request.<br> The signature is automatically anchored (on behalf of the owner of the signature request).<br> The signature anchor created is added to the list of signature anchors of the signature request.<br> This is a publicly accessible endpoint: authentication is not required to register a signature. 
     * @param {String} requestId Identifier of the signature request.
     * @param {module:model/SignatureRequestSign} signature Signature to register.
     * @param {module:api/SignatureRequestApi~signSignatureRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SignatureRequestSignResult}
     */
    signSignatureRequest(requestId, signature, callback) {
      let postBody = signature;
      // verify the required parameter 'requestId' is set
      if (requestId === undefined || requestId === null) {
        throw new Error("Missing the required parameter 'requestId' when calling signSignatureRequest");
      }
      // verify the required parameter 'signature' is set
      if (signature === undefined || signature === null) {
        throw new Error("Missing the required parameter 'signature' when calling signSignatureRequest");
      }

      let pathParams = {
        'requestId': requestId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth', 'JWTAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SignatureRequestSignResult;
      return this.apiClient.callApi(
        '/signatureRequest/{requestId}/sign', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateSignatureRequest operation.
     * @callback module:api/SignatureRequestApi~updateSignatureRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SignatureRequest} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a signature request.
     * Use this operation to update a signature request.<br> Only the properties `name`, `suspended`, `deadline`, `maxSignatures` and `authorizedSignees` can be modified.<br> 
     * @param {String} requestId Identifier of signature request to update.
     * @param {module:model/SignatureRequest} request SignatureRequest object to update.
     * @param {module:api/SignatureRequestApi~updateSignatureRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SignatureRequest}
     */
    updateSignatureRequest(requestId, request, callback) {
      let postBody = request;
      // verify the required parameter 'requestId' is set
      if (requestId === undefined || requestId === null) {
        throw new Error("Missing the required parameter 'requestId' when calling updateSignatureRequest");
      }
      // verify the required parameter 'request' is set
      if (request === undefined || request === null) {
        throw new Error("Missing the required parameter 'request' when calling updateSignatureRequest");
      }

      let pathParams = {
        'requestId': requestId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth', 'JWTAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SignatureRequest;
      return this.apiClient.callApi(
        '/signatureRequest/{requestId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
