/**
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.6.1
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WoleetApi);
  }
}(this, function(expect, WoleetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WoleetApi.AuthorizedSignee();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthorizedSignee', function() {
    it('should create an instance of AuthorizedSignee', function() {
      // uncomment below and update the code to test AuthorizedSignee
      //var instance = new WoleetApi.AuthorizedSignee();
      //expect(instance).to.be.a(WoleetApi.AuthorizedSignee);
    });

    it('should have the property pubKey (base name: "pubKey")', function() {
      // uncomment below and update the code to test the property pubKey
      //var instance = new WoleetApi.AuthorizedSignee();
      //expect(instance).to.be();
    });

    it('should have the property device (base name: "device")', function() {
      // uncomment below and update the code to test the property device
      //var instance = new WoleetApi.AuthorizedSignee();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new WoleetApi.AuthorizedSignee();
      //expect(instance).to.be();
    });

    it('should have the property countryCallingCode (base name: "countryCallingCode")', function() {
      // uncomment below and update the code to test the property countryCallingCode
      //var instance = new WoleetApi.AuthorizedSignee();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new WoleetApi.AuthorizedSignee();
      //expect(instance).to.be();
    });

    it('should have the property requiresOTP (base name: "requiresOTP")', function() {
      // uncomment below and update the code to test the property requiresOTP
      //var instance = new WoleetApi.AuthorizedSignee();
      //expect(instance).to.be();
    });

    it('should have the property commonName (base name: "commonName")', function() {
      // uncomment below and update the code to test the property commonName
      //var instance = new WoleetApi.AuthorizedSignee();
      //expect(instance).to.be();
    });

    it('should have the property identityURL (base name: "identityURL")', function() {
      // uncomment below and update the code to test the property identityURL
      //var instance = new WoleetApi.AuthorizedSignee();
      //expect(instance).to.be();
    });

  });

}));
