/**
 * Woleet API
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.5.2
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WoleetApi);
  }
}(this, function(expect, WoleetApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WoleetApi.X500Name();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('X500Name', function() {
    it('should create an instance of X500Name', function() {
      // uncomment below and update the code to test X500Name
      //var instane = new WoleetApi.X500Name();
      //expect(instance).to.be.a(WoleetApi.X500Name);
    });

    it('should have the property C (base name: "C")', function() {
      // uncomment below and update the code to test the property C
      //var instane = new WoleetApi.X500Name();
      //expect(instance).to.be();
    });

    it('should have the property ST (base name: "ST")', function() {
      // uncomment below and update the code to test the property ST
      //var instane = new WoleetApi.X500Name();
      //expect(instance).to.be();
    });

    it('should have the property L (base name: "L")', function() {
      // uncomment below and update the code to test the property L
      //var instane = new WoleetApi.X500Name();
      //expect(instance).to.be();
    });

    it('should have the property O (base name: "O")', function() {
      // uncomment below and update the code to test the property O
      //var instane = new WoleetApi.X500Name();
      //expect(instance).to.be();
    });

    it('should have the property OU (base name: "OU")', function() {
      // uncomment below and update the code to test the property OU
      //var instane = new WoleetApi.X500Name();
      //expect(instance).to.be();
    });

    it('should have the property CN (base name: "CN")', function() {
      // uncomment below and update the code to test the property CN
      //var instane = new WoleetApi.X500Name();
      //expect(instance).to.be();
    });

  });

}));
